### ISSUE TITLE
.pch file url change to absolute

### ISSUE THREAD

**Issue by ChaosTong** [yuchuanfeng/CFHoveringTableView#1]
the uploaded code contain your own urlpath, in the dome "/Users/yuchuanfeng/Documents/github/CFHoveringTableView/CFHoveringTableViewDemo/CFPreHeader.pch"
you can change it like this "CFHoveringTableViewDemo/CFPreHeader.pch"

**Comment by yuchuanfeng** [comment]
Yes, I will fix it, thanks very much
